[package]
name = "moonmath-exercizes-rust"
version = "0.1.0"
edition = "2021"


[dependencies]

[dev-dependencies]
roots = "0.0.8"
num-primes = "0.3.0"
rand = "0.8.4"
ark-ff = "0.4.2"
ark-poly = "0.4.2"
sha256 = "1.4.0"
hex = "0.4.3"
ark-std = "0.4.0"
itertools = "0.12.0"